---
- name: Create Build Instance
  ec2:
    image: "{{ ec2_base_image }}"
    instance_type: "{{ ec2_instance_type }}"
    keypair: "{{ ec2_keypair }}"
    region: "{{ aws_region }}"
    group: "{{ ec2_security_groups }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    instance_tags: "{{ ec2_instance_tags }}"
    assign_public_ip: "{{ assign_public_ip }}"
    wait: true
    volumes:
      - device_name: /dev/sda1
        volume_size: "{{ ec2_volume_size }}"
        delete_on_termination: true

  register: ec2_info
  tags: ec2

- name: Set EC2 Address
  set_fact: ansible_ssh_host={{ item.public_ip }}
  with_items: "{{ ec2_info.instances }}"
  tags: ec2

# Wait until SSH is available on the instance
- name: wait for instances to listen on port:22
  wait_for:
    state: started
    host: "{{ item.public_ip }}"
    port: 22
    timeout: 600
  with_items: "{{ ec2_info.instances }}"
  when: ec2_info.changed
  tags: ec2

# vim: ft=ansible
